#!/bin/sh

WIDTH=60

show_help() {
  cat << EOF
Wrap FASTA sequence lines to a specified width.

Usage: $(basename "$0") [OPTIONS] [FILE]

Options:
  -w, --width N    Line width (default: $WIDTH)
  -0               No wrapping (one line per sequence)
  -h, --help       Show this help

Examples:
  fasta-wrap genome.fa
  fasta-wrap -0 genome.fa
  zcat genome.fa.gz | fasta-wrap -w 60 | gzip > genome_wrapped.fa.gz
EOF
}

# Parse arguments
while [ $# -gt 0 ]; do
  case "$1" in
    -w|--width)
      WIDTH="$2"
      shift 2
      ;;
    -0)
      WIDTH=0
      shift
      ;;
    -h|--help)
      show_help
      exit 0
      ;;
    -*)
      echo "Error: Unknown option '$1'" >&2
      show_help >&2
      exit 1
      ;;
    *)
      FILE="$1"
      shift
      ;;
  esac
done

# Use file or stdin
if [ -z "$FILE" ]; then
  if [ -t 0 ]; then
    echo "Error: No input file specified." >&2
    show_help >&2
    exit 1
  else
    INPUT="/dev/stdin"
  fi
else
  INPUT="$FILE"
fi

# Process FASTA
awk -v width="$WIDTH" '
/^>/ {
  if (seq) {
    if (width == 0) {
      print seq
    } else {
      for (i = 1; i <= length(seq); i += width) {
        print substr(seq, i, width)
      }
    }
  }
  print
  seq = ""
  next
}
{
  seq = seq $0
}
END {
  if (seq) {
    if (width == 0) {
      print seq
    } else {
      for (i = 1; i <= length(seq); i += width) {
        print substr(seq, i, width)
      }
    }
  }
}
' "$INPUT"
